kind: pipeline
type: exec
name: default

steps:
  - name: bootstrap
    commands:
      - wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
      - mkdir -p Android/Sdk/cmdline-tools/latest
      - unzip commandlinetools-linux-8092744_latest.zip
      - mv cmdline-tools/* Android/Sdk/cmdline-tools/latest
      - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.8.1-stable.tar.xz
      - tar xvf flutter_linux_2.8.1-stable.tar.xz

  - name: fetch
    commands:
      - export JAVA_HOME="/nix/store/ij5nydadkpikrzama011z3lvd7k7cd0v-openjdk-11.0.12+7/lib/openjdk"
      - export ANDROID_SDK_ROOT="Android/Sdk"
      - export PATH=$$PATH:flutter/bin
      - yes | Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
      - Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;32.0.0"
      - Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-32"

  - name: build
    commands:
      - export JAVA_HOME="/nix/store/ij5nydadkpikrzama011z3lvd7k7cd0v-openjdk-11.0.12+7/lib/openjdk"
      - flutter/bin/flutter config --android-sdk Android/Sdk
      - flutter/bin/flutter pub get
      - flutter/bin/flutter build apk