kind: pipeline
type: exec
name: release

steps:
  - name: build
    commands:
      - nixos-container stop isolated
      - nixos-container start isolated
      - eval `ssh-agent -s`
      - echo "$SSH_PRIVATE_KEY" | ssh-add -
      - scp -r `pwd` isolated:/var/lib/builder
      - ssh isolated "cd src && flutter build apk --split-per-abi"
      - scp isolated:/var/lib/builder/src/build/app/outputs/flutter-apk/*-release.apk `pwd`
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY

  - name: deploy
    commands:
      - rename app pro.kherel.selfprivacy *.apk && rename release `git rev-parse --short HEAD` *.apk
      - ls *.apk

node:
  server: builder
