#kind: pipeline
#type: exec
#name: Continuous Integration
#
#steps:
#
#trigger:
#  event:
#    - push
#    - pull_request
#
#node:
#  server: builder
#
#---

kind: pipeline
type: exec
name: Release

environment:
  HOME: /var/lib/drone-runner-exec

steps:
  - name: Debug
    commands:
      - echo $HOME
      - podman images
      - ls -la

  - name: Build Intermediate Linux Release Artifact (Binary)
    commands:
      - ./ci.sh --build-linux
    environment:
      STANDALONE_KEYSTORE_PASS:
        from_secret: STANDALONE_KEYSTORE_PASS
      FDROID_KEYSTORE_PASS:
        from_secret: FDROID_KEYSTORE_PASS

  - name: Build Intermediate Android Release Artifact (.APK)
    commands:
      - ./ci.sh --build-apk
    environment:
      STANDALONE_KEYSTORE_PASS:
        from_secret: STANDALONE_KEYSTORE_PASS
      FDROID_KEYSTORE_PASS:
        from_secret: FDROID_KEYSTORE_PASS

  - name: Sign Android Release Artifact (.APK) for Standalone Use
    commands:
      - ./ci.sh --sign-apk-standalone
    environment:
      STANDALONE_KEYSTORE_PASS:
        from_secret: STANDALONE_KEYSTORE_PASS
      FDROID_KEYSTORE_PASS:
        from_secret: FDROID_KEYSTORE_PASS

  - name: Sign Android Release Artifact (.APK) for F-Droid Repository
    commands:
      - ./ci.sh --sign-apk-fdroid
    environment:
      STANDALONE_KEYSTORE_PASS:
        from_secret: STANDALONE_KEYSTORE_PASS
      FDROID_KEYSTORE_PASS:
        from_secret: FDROID_KEYSTORE_PASS

  - name: Package Linux AppImage Artifact
    commands:
      - ./ci.sh --package-linux-appimage

  - name: Package Linux Flatpak Artifact
    commands:
      - ./ci.sh --package-linux-flatpak

  - name: Package Linux Archive Artifact
    commands:
      - ./ci.sh --package-linux-archive

trigger:
  event:
    - tag

node:
  server: builder
