kind: pipeline
type: exec
name: default

steps:
  - name: build
    commands:
      #- nix-shell --pure --run "flutter doctor -v"
      #- nix-shell --pure --run "dart --version"
      - nix-shell --pure --run "flutter build apk --split-per-abi"
    environment:
      NIX_PATH: "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs"
      NIXPKGS_ALLOW_UNFREE: 1
