kind: pipeline
type: exec
name: debug

steps:
  - name: test
    commands:
      - sudo nixos-container stop isolated
      - sudo nixos-container start isolated
      - eval `ssh-agent -s`
      - echo "$SSH_PRIVATE_KEY" | ssh-add -
      - scp -r `pwd` isolated:/var/lib/builder
      - ssh isolated "cd src && flutter build apk --split-per-abi"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY

node:
  server: builder
