kind: pipeline
type: exec
name: default

steps:
  - name: bootstrap
    commands:
      - wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
      - mkdir -p Android/Sdk/cmdline-tools/latest
      - unzip commandlinetools-linux-8092744_latest.zip
      - mv cmdline-tools/* Android/Sdk/cmdline-tools/latest
      - ls Android/Sdk/cmdline-tools/latest

  - name: fetch
    commands:
      - export JAVA_HOME="/nix/store/ij5nydadkpikrzama011z3lvd7k7cd0v-openjdk-11.0.12+7/lib/openjdk"
      - export ANDROID_SDK_ROOT="Android/Sdk"
      - yes | Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
      - Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;32.0.0"
      - Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-32"

  - name: build
    commands:
      - export JAVA_HOME="/nix/store/ij5nydadkpikrzama011z3lvd7k7cd0v-openjdk-11.0.12+7/lib/openjdk"
      - flutter config --android-sdk Android/Sdk
      - flutter pub get
      - flutter build apk