kind: pipeline
type: exec
name: debug

steps:
  - name: test
    commands:
      - eval `ssh-agent -s`
      - echo "$SSH_PRIVATE_KEY" | ssh-add -
      - ssh isolated echo hello
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY

node:
  server: builder
