targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            DateTime:
              type: DateTime
              fromJsonFunctionName: dateTimeFromJson
              toJsonFunctionName: dateTimeToJson
              import: package:selfprivacy/utils/scalars.dart
          clients:
            - graphql
            - graphql_flutter
      json_serializable:
        options:
          create_factory: true
          create_to_json: false
