name: selfprivacy
grade: stable
adopt-info: selfprivacy-part
icon: assets/images/icon/logo.svg
base: core24
confinement: strict
platforms:
  amd64:
  arm64:
apps:
  selfprivacy:
    command: selfprivacy
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: selfprivacy
    desktop: usr/share/applications/selfprivacy.desktop

parts:
  flutter-part:
    source: https://github.com/flutter/flutter.git
    plugin: nil
    override-pull: |
      set -eux
      FLUTTER_VERSION="3.35.7"
      echo "Using Flutter version: $FLUTTER_VERSION"
      git clone --recursive --branch "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$CRAFT_PART_SRC"
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''
  selfprivacy-part:
    after: [ flutter-part ]
    plugin: nil
    #plugin: flutter
    source: .
    build-snaps:
      - cmake
    build-packages:
      - curl
      - libsecret-1-dev
      - libjsoncpp-dev
      - clang
      - ninja-build
      - pkg-config
      - lld
      - llvm
    override-build: |
      craftctl default
      set -eux
      cd $CRAFT_PART_SRC_WORK
      flutter pub get || true
      flutter build linux --release --verbose
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
      mkdir -p $CRAFT_PART_INSTALL/metainfo
      cp selfprivacy.metainfo.xml $CRAFT_PART_INSTALL/metainfo/selfprivacy.metainfo.xml
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cp selfprivacy.desktop $CRAFT_PART_INSTALL/usr/share/applications/selfprivacy.desktop
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps
      cp assets/images/icon/logo.svg $CRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/selfprivacy.svg
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
    parse-info: [ metainfo/selfprivacy.metainfo.xml ]
