name: Build CI

on:
  push:
    branches:
      - master
      - bttmchnd/ci-rehaul-p2
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  # Linux targets
  build-linux-nix:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-nix

  # build-linux-generic:
  #   runs-on:
  #     - x86
  #     - kvm

  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: nix build .#linux-generic

  build-linux-portable:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-portable

  build-linux-flatpak:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-flatpak
      - uses: actions/upload-artifact@v3
        with:
          name: linux-flatpak
          path: result/*

  # build-linux-appimage-generic:
  #   runs-on:
  #     - x86
  #     - kvm

  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: nix build .#linux-appimage-generic -o artifact-appimage-generic

  build-linux-appimage-portable:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-appimage-portable
      - uses: actions/upload-artifact@v3
        with:
          name: linux-appimage-portable
          path: result/*

  # build-linux-archive-generic:
  #   runs-on:
  #     - x86
  #     - kvm

  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: nix build .#linux-archive-generic -o artifact-archive-generic

  build-linux-archive-portable:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-archive-portable
      - uses: actions/upload-artifact@v3
        with:
          name: linux-archive-portable
          path: result/*

  # Android targets
  build-android-nightly-fdroid:
    runs-on:
      - x86
      - kvm

    env:
      CI_KEYSTORE_FILE: fdroid-keystore.jks
      CI_KEYSTORE_PASS: ${{ secrets.CI_KEYSTORE_PASS_FDROID }}

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#android-apk-release-nightly
      - run: echo "${{ secrets.CI_KEYSTORE_FILE_FDROID }}" | base64 -d > $CI_KEYSTORE_FILE
      - run: nix run .#sign-android-fdroid result/*.apk
      - uses: actions/upload-artifact@v3
        with:
          name: android-nightly-fdroid
          path: selfprivacy-fdroid-signed.apk
      - run: |
          export CI_SHA="${{ forge.sha }}"
          eval $(ssh-agent -s)
          echo "$CI_DEPLOYER_SSH_KEY" | tr -d '\r' | ssh-add -
          scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null selfprivacy-fdroid-signed.apk deployer@selfprivacy.org:/var/www/fdroid.selfprivacy.org/repo/selfprivacy-fdroid-nightly-$(date -I)-${CI_SHA:0:6}.apk
          ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null deployer@selfprivacy.org "cd /var/www/fdroid.selfprivacy.org && fdroid update --create-metadata"

  # Darwin targets
  build-macos:
    runs-on:
      - macos

    env:
      ALL_PROXY: ${{ vars.CI_MACOS_ALL_PROXY }}
      all_proxy: ${{ vars.CI_MACOS_ALL_PROXY }}

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#macos -o artifact-macos
      - run: OLDDIR=$PWD; (cd artifact-macos && zip -r "$OLDDIR/selfprivacy-macos-${{ forgejo.ref_name }}.zip" .)
      - uses: actions/upload-artifact@v3
        with:
          name: macos-release
          path: selfprivacy-macos-${{ forgejo.ref_name }}.zip


  build-ios:
    runs-on:
      - macos

    env:
      ALL_PROXY: ${{ vars.CI_MACOS_ALL_PROXY }}
      all_proxy: ${{ vars.CI_MACOS_ALL_PROXY }}

    steps:
      - uses: actions/checkout@v6
      - run: nix run .#build-ios -- ipa release
      - run: zip -r "selfprivacy-ios-${{ forgejo.ref_name }}.zip" Runner.xcarchive
      - uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: selfprivacy-ios-${{ forgejo.ref_name }}.zip

  # Windows targets
  build-windows:
    runs-on:
      - windows

    steps:
      - uses: actions/checkout@v6
      - run: flutter config --no-analytics
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get --no-precompile --enforce-lockfile
      - run: flutter build windows --release
