name: Build CI

on:
  push:
    branches:
      - master
      - bttmchnd/ci-rehaul-p2
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  # Linux targets
  build-linux-nix:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-nix

  # build-linux-generic:
  #   runs-on:
  #     - x86
  #     - kvm

  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: nix build .#linux-generic

  build-linux-portable:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-portable

  build-linux-flatpak:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-flatpak
      - uses: actions/upload-artifact@v3
        with:
          name: linux-flatpak
          path: result/*

  # build-linux-appimage-generic:
  #   runs-on:
  #     - x86
  #     - kvm

  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: nix build .#linux-appimage-generic -o artifact-appimage-generic

  build-linux-appimage-portable:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-appimage-portable
      - uses: actions/upload-artifact@v3
        with:
          name: linux-appimage-portable
          path: result/*

  # build-linux-archive-generic:
  #   runs-on:
  #     - x86
  #     - kvm

  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: nix build .#linux-archive-generic -o artifact-archive-generic

  build-linux-archive-portable:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#linux-archive-portable
      - uses: actions/upload-artifact@v3
        with:
          name: linux-archive-portable
          path: result/*

  # Android targets
  build-android-production:
    runs-on:
      - x86
      - kvm

    env:
      CI_KEYSTORE_FILE: google-keystore.jks
      CI_KEYSTORE_PASS: ${{ secrets.CI_KEYSTORE_PASS_GOOGLE }}

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#android-aab-release-production
      - run: echo "${{ secrets.CI_KEYSTORE_FILE_GOOGLE }}" | base64 -d > google-keystore.jks
      - run: nix run .#sign-android-google result/*.aab
      - uses: actions/upload-artifact@v3
        with:
          name: android-production-google
          path: selfprivacy-google-signed.aab


  build-android-fdroid:
    runs-on:
      - x86
      - kvm

    env:
      CI_KEYSTORE_FILE: fdroid-keystore.jks
      CI_KEYSTORE_PASS: ${{ secrets.CI_KEYSTORE_PASS_FDROID }}

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#android-apk-release-fdroid
      - run: echo "${{ secrets.CI_KEYSTORE_FILE_FDROID }}" | base64 -d > fdroid-keystore.jks
      - run: nix run .#sign-android-fdroid result/*.apk
      - uses: actions/upload-artifact@v3
        with:
          name: android-production-fdroid
          path: selfprivacy-fdroid-signed.apk

  build-android-nightly:
    runs-on:
      - x86
      - kvm

    env:
      CI_KEYSTORE_FILE: nightly-keystore.jks
      CI_KEYSTORE_PASS: ${{ secrets.CI_KEYSTORE_PASS_NIGHTLY }}

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#android-apk-release-nightly
      - run: echo "${{ secrets.CI_KEYSTORE_FILE_NIGHTLY }}" | base64 -d > nightly-keystore.jks
      - run: nix run .#sign-android-nightly result/*.apk
      - uses: actions/upload-artifact@v3
        with:
          name: android-production-nightly
          path: selfprivacy-nightly-signed.apk


  # Darwin targets
  build-macos:
    runs-on:
      - macos

    steps:
      - uses: actions/checkout@v6
      - run: nix build .#macos -o artifact-macos

  build-ios:
    runs-on:
      - macos

    steps:
      - uses: actions/checkout@v6
      - run: nix run .#build-ios -- ipa release

  # Windows targets
  build-windows:
    runs-on:
      - windows

    steps:
      - uses: actions/checkout@v6
      - run: flutter config --no-analytics
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get --no-precompile --enforce-lockfile
      - run: flutter build windows --release
