name: Generic CI

on:
  push:
    branches:
      - master
      - bttmchnd/ci-rehaul-p2
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  analyze:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix run .#analyze-flutter

  scan:
    runs-on:
      - x86
      - kvm

    steps:
      - uses: actions/checkout@v6
      - run: nix run .#scan-sonarqube
