// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:selfprivacy/logic/models/hive/backblaze_bucket.dart';
import 'package:selfprivacy/logic/models/hive/backups_credential.dart';
import 'package:selfprivacy/logic/models/hive/dns_provider_credential.dart';
import 'package:selfprivacy/logic/models/hive/email_password_metadata.dart';
import 'package:selfprivacy/logic/models/hive/server.dart';
import 'package:selfprivacy/logic/models/hive/server_details.dart';
import 'package:selfprivacy/logic/models/hive/server_domain.dart';
import 'package:selfprivacy/logic/models/hive/server_provider_credential.dart';
import 'package:selfprivacy/logic/models/hive/user.dart';
import 'package:selfprivacy/logic/models/hive/wizards_data/server_installation_wizard_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BackblazeBucketAdapter());
    registerAdapter(BackupsCredentialAdapter());
    registerAdapter(BackupsProviderTypeAdapter());
    registerAdapter(DnsProviderCredentialAdapter());
    registerAdapter(DnsProviderTypeAdapter());
    registerAdapter(EmailPasswordMetadataAdapter());
    registerAdapter(ServerAdapter());
    registerAdapter(ServerDomainAdapter());
    registerAdapter(ServerHostingDetailsAdapter());
    registerAdapter(ServerInstallationWizardDataAdapter());
    registerAdapter(ServerProviderCredentialAdapter());
    registerAdapter(ServerProviderTypeAdapter());
    registerAdapter(ServerProviderVolumeAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BackblazeBucketAdapter());
    registerAdapter(BackupsCredentialAdapter());
    registerAdapter(BackupsProviderTypeAdapter());
    registerAdapter(DnsProviderCredentialAdapter());
    registerAdapter(DnsProviderTypeAdapter());
    registerAdapter(EmailPasswordMetadataAdapter());
    registerAdapter(ServerAdapter());
    registerAdapter(ServerDomainAdapter());
    registerAdapter(ServerHostingDetailsAdapter());
    registerAdapter(ServerInstallationWizardDataAdapter());
    registerAdapter(ServerProviderCredentialAdapter());
    registerAdapter(ServerProviderTypeAdapter());
    registerAdapter(ServerProviderVolumeAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserTypeAdapter());
  }
}
