part of 'porkbun_dns_info.dart';

PorkbunDnsRecord _fromDnsRecord(
  final DnsRecord dnsRecord,
  final String rootDomain,
) {
  final String type = dnsRecord.type;
  final String content = dnsRecord.content ?? '';
  String name = dnsRecord.name ?? '';
  if (name == '@' || name == rootDomain) {
    name = '';
  }

  return PorkbunDnsRecord(
    name: name,
    type: type,
    ttl: dnsRecord.ttl.toString(),
    content: content,
    prio: dnsRecord.priority.toString(),
    notes: 'Generated by SelfPrivacy app',
  );
}

DnsRecord _toDnsRecord(
  final PorkbunDnsRecord porkbunRecord,
  final String rootDomain,
) {
  final String type = porkbunRecord.type;
  String name = porkbunRecord.name;
  if (name == rootDomain) {
    name = '';
  } else if (name.endsWith('.$rootDomain')) {
    name = name.substring(0, name.length - rootDomain.length - 1);
  }

  if (name.isEmpty) {
    name = rootDomain;
  }

  int? priority;
  if (type == 'MX') {
    priority = int.parse(porkbunRecord.prio ?? '10');
  }

  return DnsRecord(
    name: name,
    type: type,
    ttl: int.parse(porkbunRecord.ttl),
    content: porkbunRecord.content,
    priority: priority ?? 10,
  );
}

ServerDomain _toServerDomain(final PorkbunDomain porkbunDomain) => ServerDomain(
  domainName: porkbunDomain.domain,
  provider: DnsProviderType.porkbun,
);
