on: push

env: # Or as an environment variable
  GITEA_RELEASE_TOKEN: ${{ secrets.GITEA_RELEASE_TOKEN }}

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter build macos
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release/selfprivacy.app

  deploy:
    runs-on: ubuntu-latest
    needs:
      - windows
      - macos
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: windows
          path: windows-release
      - uses: actions/download-artifact@v3
        with:
          name: macos
          path: macos-release/selfprivacy.app
      - run: pushd windows-release; zip -r ../selfprivacy-windows.zip .; popd
      - run: pushd macos-release; zip -r ../selfprivacy-macos.zip .; popd
      - run: ./ci.py --gitea-upload-attachment selfprivacy-windows.zip
      - run: ./ci.py --gitea-upload-attachment selfprivacy-macos.zip
